"""Render Omarchy themes into WezTerm, Ghostty and Claude Code theme files for this repo.

Reproduces Omarchy's own templates (MIT, see LICENSE-omarchy):
  - palette mapping from default/themed/ghostty.conf.tpl
  - Claude Code overrides from default/themed/claude.json.tpl
  - colour fallbacks and mix() from bin/omarchy-theme-color / bin/omarchy-theme-set-templates

Usage:
  git clone --depth 1 https://github.com/basecamp/omarchy /tmp/omarchy
  python3 tools/omarchy-themes/omarchy_themes.py /tmp/omarchy
Themes in extra-themes/ (e.g. dracula) are rendered too. Output goes into home/.
"""
import glob, json, os, re, sys, tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
HOME_SRC = os.path.normpath(os.path.join(HERE, "..", "..", "home"))
OUT = {
    "wezterm": os.path.join(HOME_SRC, "private_dot_config", "wezterm", "colors"),
    "ghostty": os.path.join(HOME_SRC, "private_dot_config", "ghostty", "themes"),
    "claude": os.path.join(HOME_SRC, "dot_claude", "themes"),
}

MIX_RE = re.compile(r"\{\{\s*mix\s+(\w+)\s+(\w+)\s+([0-9.]+)%?\s*\}\}")
VAR_RE = re.compile(r"\{\{\s*(\w+)\s*\}\}")


def mix(a, b, pct):
    """Omarchy mix: start*(1-amount) + end*amount, rounded half up."""
    t = pct / 100
    ca = [int(a[i:i + 2], 16) for i in (1, 3, 5)]
    cb = [int(b[i:i + 2], 16) for i in (1, 3, 5)]
    return "#" + "".join(f"{int(x * (1 - t) + y * t + 0.5):02x}" for x, y in zip(ca, cb))


def load(path):
    c = {k: (v.lower() if isinstance(v, str) and v.startswith("#") else v)
         for k, v in tomllib.load(open(path, "rb")).items()}
    c.setdefault("mode", c.get("theme_type", "dark"))
    c.setdefault("bright_foreground", c["foreground"])
    c.setdefault("muted", c.get("dark_foreground", c["foreground"]))
    c.setdefault("selection", c.get("selection_background", c["muted"]))
    c.setdefault("selection_background", c["selection"])
    c.setdefault("selection_foreground", c["bright_foreground"])
    for k in ("red", "yellow", "green", "cyan", "blue", "magenta"):
        c.setdefault("bright_" + k, mix(c[k], "#ffffff", 20))
    c["theme_type"] = c["mode"]
    return c


def render(tpl, ctx):
    out = MIX_RE.sub(lambda m: mix(ctx[m[1]], ctx[m[2]], float(m[3])), tpl)
    return VAR_RE.sub(lambda m: str(ctx[m[1]]), out)


def main(omarchy):
    for d in OUT.values():
        os.makedirs(d, exist_ok=True)
    claude_tpl = open(os.path.join(HERE, "templates", "claude.json.tpl")).read()
    ghostty_tpl = open(os.path.join(HERE, "templates", "ghostty.conf.tpl")).read()
    paths = sorted(glob.glob(os.path.join(omarchy, "themes", "*", "colors.toml")))
    paths += sorted(glob.glob(os.path.join(HERE, "extra-themes", "*", "colors.toml")))
    for path in paths:
        slug = path.split(os.sep)[-2]
        title = "Omarchy " + " ".join(w.capitalize() for w in slug.split("-"))
        c = load(path)
        bg, fg = c["background"], c["foreground"]
        ansi = [bg, c["red"], c["green"], c["yellow"], c["blue"], c["magenta"], c["cyan"], fg]
        brights = [c["muted"], c["bright_red"], c["bright_green"], c["bright_yellow"],
                   c["bright_blue"], c["bright_magenta"], c["bright_cyan"], c["bright_foreground"]]
        q = lambda xs: "[" + ", ".join(f"'{x}'" for x in xs) + "]"
        tab_bg = c.get("dark_background", mix(bg, "#000000", 25))
        wez = f"""# Generated by tools/omarchy-themes from Omarchy theme '{slug}' (MIT, basecamp/omarchy)
[metadata]
name = '{title}'

[colors]
foreground = '{fg}'
background = '{bg}'
cursor_bg = '{c["bright_foreground"]}'
cursor_border = '{c["bright_foreground"]}'
cursor_fg = '{bg}'
selection_bg = '{c["selection_background"]}'
selection_fg = '{c["selection_foreground"]}'
split = '{c["muted"]}'
scrollbar_thumb = '{c["muted"]}'
ansi = {q(ansi)}
brights = {q(brights)}

[colors.tab_bar]
background = '{tab_bg}'

[colors.tab_bar.active_tab]
bg_color = '{c["accent"]}'
fg_color = '{bg}'

[colors.tab_bar.inactive_tab]
bg_color = '{tab_bg}'
fg_color = '{c["muted"]}'

[colors.tab_bar.new_tab]
bg_color = '{tab_bg}'
fg_color = '{c["muted"]}'
"""
        with open(os.path.join(OUT["wezterm"], f"omarchy-{slug}.toml"), "w", newline="\n") as f:
            f.write(wez)
        with open(os.path.join(OUT["ghostty"], f"omarchy-{slug}"), "w", newline="\n") as f:
            f.write(f"# Generated by tools/omarchy-themes from Omarchy theme '{slug}'\n")
            f.write(render(ghostty_tpl, c))
        doc = json.loads(render(claude_tpl, c))
        doc["name"] = title
        with open(os.path.join(OUT["claude"], f"omarchy-{slug}.json"), "w", newline="\n") as f:
            json.dump(doc, f, indent=2)
            f.write("\n")
        print(f"{slug:16} {c['mode']:5} bg={bg} accent={c['accent']}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/omarchy")
